name: Sync Markdown to Hatena Blog

on:
  push:
    paths:
      - "articles/**/*.md"
      - "_drafts/**/*.md"
  workflow_dispatch:

permissions:
  contents: write  # GITHUB_TOKEN に書き込み権限を付与

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Python 環境をセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: 必要なライブラリをインストール
        run: pip install requests

      - name: はてなブログへ Markdown 記事を同期
        run: python .github/scripts/sync_md.py
        env:
          HATENA_ID: ${{ secrets.HATENA_ID }}
          HATENA_API_KEY: ${{ secrets.HATENA_API_KEY }}
          MEDIA_BASE_URL: "https://raw.githubusercontent.com/harayoki/curryoki/refs/heads/main"

      - name: Git リモート URL を設定
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: コミット & プッシュ `published.json / missing.json`
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata/published.json
          git add metadata/missing.json
          git commit -m "Update published.json [CI]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
